name: "spray"
version: 4.0.11-beta.4
usage: "upgrade sub-charts from an umbrella chart with dependency orders"
description: "Helm plugin for upgrading sub-charts from umbrella chart with dependency orders"
command: "$HELM_PLUGIN_DIR/bin/helm-spray"
hooks:
  install: "cd $HELM_PLUGIN_DIR; scripts/install_plugin_locally.sh"
  update: "cd $HELM_PLUGIN_DIR; scripts/install_plugin_locally.sh"
ignoreFlags: false
useTunnel: false
