name: Release on internal github
on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:
    name: Make release
    runs-on: [self-hosted]
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.19'
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          path: ${{ github.workspace }}/src/github.com/gemalto/helm-spray
      - name: Make release
        run: |
          cd ${{ github.workspace }}/src/github.com/gemalto/helm-spray
          make dist
      - name: Publish release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: false
          files: ${{ github.workspace }}/src/github.com/gemalto/helm-spray/_dist/helm-spray*
